server:
  port: 7000
spring:
  application:
    name: servicio-coches
eureka:
  instance:
    instance-id: intanciaB
    hostname: a13e100
  client:
    serviceUrl:
      defaultZone: http://10.1.3.100:8761/eureka