spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/UsuariosCursoRealm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  application:
    name: servicio-libreria
  config:
    import:
    - optional:configserver:http://${HOST_CONFIG}:8888